### ISSUE TITLE
Saving 'Add a New Book' form should bring you to completed Book page

### ISSUE THREAD

**Issue by ruth-farrell** [staplesad/flask_bookclub#18]
When you 'Add a new book' and press 'Save' it should bring you to the 'Book' page instead of leaving you on the NewBook page, so that you can see your saved book.  If you get me. 

Note: It does this correctly when you edit the book but not when you're adding it new.

**Comment by staplesad** [comment]
Cool I'll have a look.

**Comment by staplesad** [comment]
I messed up the indentation. Should be fixed now.
