### ISSUE TITLE
Create website/page before the sign in page. 

### ISSUE THREAD

**Issue by ruth-farrell** [staplesad/flask_bookclub#22]

**Comment by ruth-farrell** [comment]
Okay. So I've created a basic homepage/index.html of this but I'm not entirely sure how to organise this. I think that it should have its own folder with its own JS and CSS folder inside of that as it would be good to keep it separate from the actual app since it's just the outer website part and it's bound to be very different?  Would this then be able to link to the 'sign in page'?  @staplesad

**Comment by staplesad** [comment]
It's part of the app so it should use the same folders. It could have its own files within those though. If it doesn't need any of the app information (which is shouldn't as its visible to people not signed in) it can be a static html page stored in the static folder. To prevent confusion it would be better if its not called index.html as that's used to refer to the main page that appears when signed in. I might have to rearrange some stuff on the python end. Maybe you could upload the page and I could have a look at doing that? @ruth-farrell

**Comment by staplesad** [comment]
Ok I think I've figured out the way to do it. I can load up my code with a holding place page and then you could replace it? @ruth-farrell

**Comment by ruth-farrell** [comment]
Sounds good!  
Edit: Sorry I didn't see the first message for some reason!   
@staplesad 

Yep that's exactly what I mean.. inside the main Flask_Bookclub folder but separated out from the rest of the templates css etc. within its own folder. Inside Static sounds good... could we give it it's own folder there? It's going to have it's own CSS page and probably it's own images etc.  And if we're thinking longterm it would probably have to progress to including at least an 'about' page but probably also a contact page, terms and conditions etc. so it's worth organising it right, now.

**Comment by staplesad** [comment]
If we want it to use the same bar as the other pages it'll need to be a template page rather than static. You can link it to its own css & javascript from there as well though. Maybe we should draw something up to record what we want the flow of the site to be and I can think about how to arrange it from there?

**Comment by staplesad** [comment]
@ruth-farrell ok so based on the way you wrote the home page and the about page I made them static html files rather than dynamic ones which get information from python/the database. so they're stored in the static folder. all the links and that should still work.
