### ISSUE TITLE
Database of book quotes.

### ISSUE THREAD

**Issue by ruth-farrell** [staplesad/flask_bookclub#6]
To appear in the app as you move around it.

**Comment by staplesad** [comment]
Added quote table to database and populated with an initial 5 quotes. The quotes displayed are now picked at random from this table. Let me know if you want to add any more.

**Comment by ruth-farrell** [comment]
Excellent looks really good!! 💃

**Comment by ruth-farrell** [comment]
Problemo: 

![image](https://user-images.githubusercontent.com/29253565/27051211-2e66d604-4fad-11e7-8fc3-d644f59732ec.png)

Because I don't have the database, I assume?

**Comment by staplesad** [comment]
Is that error still showing up for you @ruth-farrell ? Ah shit yeah I see the problem. I'll send you a script which should fix it.
