### ISSUE TITLE
Future Feature: Book Wish List

### ISSUE THREAD

**Issue by ruth-farrell** [staplesad/flask_bookclub#7]
A wish list where you add your own books to it and also a way for you to recommend individual books to certain people outside of the book club.

**Comment by staplesad** [comment]
Added new branch with some work on this. Doesn't look the best atm but is functional. Let me know what other functions would be good.

**Comment by staplesad** [comment]
Merged this branch with public so public branch now has the first version of this feature.

**Comment by ruth-farrell** [comment]
Loving this so far! But one thing:
Another possible option for layout:  

How about putting the wishlist on the homepage under the Book Club list. And then maybe index.html could be like: Bookclub Discussion List, Quote, My Reading List.  And then maybe we could have one menu item called 'Add Book' and when you go in you have two options: 'Suggest Book for Bookclub' or  'Add Book to Reading List' and then those buttons bring you to the right form?  

It means then we're grouping similar functionalities together, ye know?

**Comment by staplesad** [comment]
Yeah makes sense. I'll have a look. Should I keep it on top as well?

**Comment by ruth-farrell** [comment]
I think... no for now. We can always add it back later. But if it's on top we'd also have to have a Bookclub Discussion label is well and I don't think we need that yet anyways.

**Comment by staplesad** [comment]
Ok made the changes you mentioned. But the css stylings of them will definitely have to be looked at by you sorry :/ Not live yet either, i figure i'll wait a bit before updating that. Also some of the wording should probably be changed. You were thinking Reading List?

**Comment by ruth-farrell** [comment]
Maybe Reading List yeah? I think that gives you a better idea of what it is. But we could always change that later! 

Just wanted to note here that via CSS I need to change the 'New Book' menu into a dropdown with two options: 'Suggest Book for Bookclub' or 'Add Book to Reading List'.  I think that makes more sense instead of having a page with two buttons. 

Also we might consider changing the menu option from New Book to Add Book?

**Comment by staplesad** [comment]
yep both of those sound like good changes. I'll go through and try to change all references to Reading List so, let me know if I miss any.

**Comment by ruth-farrell** [comment]
Also. While we're here we also might consider changing the name "Bookclub App". It's confusing for people that don't know that you can have a web applications​? They will assume it's a mobile app ye know?  Would be good to have a somewhat creative name too. Worth thinking about!

**Comment by staplesad** [comment]
Yep. I'm terrible at that stuff so if you guys come up with something else I'm all ears.

**Comment by ruth-farrell** [comment]
How about displaying on the Reading List on the Homepage a "view book" button instead of "edit" and delete" and then when you click into "view book" you can edit/delete the book and even maybe leave a review (so exactly like our books in the bookclub). I think people might like to leave reviews so that if they forget later how good it was they can look back on it?   

In the future is well it would be good to tag books as either "Read" or "Want to Read".  And then you can look back and see easily what you've read and whether you liked it or not, when you did read it.

**Comment by staplesad** [comment]
I was thinking the info section could function as a place to record review type thoughts basically. I could increase the size of the text stored in there though? The tag thing is a good idea, i'll add it in a separate issue so I don't forget. Should be easy enough to switch the list to more like the bookclub list.

**Comment by staplesad** [comment]
I'm going to close this as it is mostly implemented and integrated at this point. Any further improvements can be opened as a separate issue.
